"""add_recipient_cc_list_to_documents

Revision ID: 73c13274d691
Revises: 1b2c3d4e5f6a
Create Date: 2026-05-09 06:29:39.580338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73c13274d691'
down_revision = '1b2c3d4e5f6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_async_tasks_created_at'), 'async_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_async_tasks_task_status'), 'async_tasks', ['task_status'], unique=False)
    op.create_index(op.f('ix_document_approval_logs_doc_id'), 'document_approval_logs', ['doc_id'], unique=False)
    op.create_index(op.f('ix_document_snapshots_created_at'), 'document_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_document_snapshots_doc_id'), 'document_snapshots', ['doc_id'], unique=False)
    op.add_column('documents', sa.Column('recipient', sa.String(length=512), nullable=True))
    op.add_column('documents', sa.Column('cc_list', sa.Text(), nullable=True))
    op.drop_index('idx_document_number', table_name='documents')
    op.create_index(op.f('ix_documents_creator_id'), 'documents', ['creator_id'], unique=False)
    op.create_index(op.f('ix_documents_dept_id'), 'documents', ['dept_id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_exemplar_documents_content_hash'), 'exemplar_documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_exemplar_documents_doc_type_id'), 'exemplar_documents', ['doc_type_id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_hierarchy_dept_id'), 'knowledge_base_hierarchy', ['dept_id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_hierarchy_owner_id'), 'knowledge_base_hierarchy', ['owner_id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_hierarchy_parent_id'), 'knowledge_base_hierarchy', ['parent_id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_hierarchy_physical_file_id'), 'knowledge_base_hierarchy', ['physical_file_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_dept_id'), 'knowledge_chunks', ['dept_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_is_deleted'), 'knowledge_chunks', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_kb_id'), 'knowledge_chunks', ['kb_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_owner_id'), 'knowledge_chunks', ['owner_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_physical_file_id'), 'knowledge_chunks', ['physical_file_id'], unique=False)
    op.create_index(op.f('ix_nbs_workflow_audit_action_timestamp'), 'nbs_workflow_audit', ['action_timestamp'], unique=False)
    op.create_index(op.f('ix_nbs_workflow_audit_doc_id'), 'nbs_workflow_audit', ['doc_id'], unique=False)
    op.create_index(op.f('ix_user_notifications_created_at'), 'user_notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_notifications_doc_id'), 'user_notifications', ['doc_id'], unique=False)
    op.create_index(op.f('ix_user_notifications_is_read'), 'user_notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_user_notifications_user_id'), 'user_notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_sessions_expires_at'), 'users_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_users_sessions_user_id'), 'users_sessions', ['user_id'], unique=False)
    op.drop_column('users_sessions', 'access_jti')
    op.drop_column('users_sessions', 'device_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_sessions', sa.Column('device_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users_sessions', sa.Column('access_jti', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_sessions_user_id'), table_name='users_sessions')
    op.drop_index(op.f('ix_users_sessions_expires_at'), table_name='users_sessions')
    op.drop_index(op.f('ix_user_notifications_user_id'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_is_read'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_doc_id'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_created_at'), table_name='user_notifications')
    op.drop_index(op.f('ix_nbs_workflow_audit_doc_id'), table_name='nbs_workflow_audit')
    op.drop_index(op.f('ix_nbs_workflow_audit_action_timestamp'), table_name='nbs_workflow_audit')
    op.drop_index(op.f('ix_knowledge_chunks_physical_file_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_owner_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_kb_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_is_deleted'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_dept_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_base_hierarchy_physical_file_id'), table_name='knowledge_base_hierarchy')
    op.drop_index(op.f('ix_knowledge_base_hierarchy_parent_id'), table_name='knowledge_base_hierarchy')
    op.drop_index(op.f('ix_knowledge_base_hierarchy_owner_id'), table_name='knowledge_base_hierarchy')
    op.drop_index(op.f('ix_knowledge_base_hierarchy_dept_id'), table_name='knowledge_base_hierarchy')
    op.drop_index(op.f('ix_exemplar_documents_doc_type_id'), table_name='exemplar_documents')
    op.drop_index(op.f('ix_exemplar_documents_content_hash'), table_name='exemplar_documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_dept_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_creator_id'), table_name='documents')
    op.create_index('idx_document_number', 'documents', ['document_number'], unique=False)
    op.drop_column('documents', 'cc_list')
    op.drop_column('documents', 'recipient')
    op.drop_index(op.f('ix_document_snapshots_doc_id'), table_name='document_snapshots')
    op.drop_index(op.f('ix_document_snapshots_created_at'), table_name='document_snapshots')
    op.drop_index(op.f('ix_document_approval_logs_doc_id'), table_name='document_approval_logs')
    op.drop_index(op.f('ix_async_tasks_task_status'), table_name='async_tasks')
    op.drop_index(op.f('ix_async_tasks_created_at'), table_name='async_tasks')
    # ### end Alembic commands ###